[ODS-4801] MetaEd integration build for Transcript and Transportation Extensions
Ed-Fi-Alliance-OSS/Ed-Fi-Extensions pull request #24
Opened 2021-03-26 15:13 UTC by semalaiappan

2021-03-29 16:20 UTC, jamessmckay approved these changes

2021-03-29 16:23 UTC, jamessmckay requested changes
Code Gen build is broken, need a pull request for codegen that fixes the approval tests.

2021-03-30 19:49 UTC, semalaiappan commented
@jamessmckay  I fixed codegen issue and approval test . Thanks  . Ready for review again

2021-03-31 20:57 UTC, jamessmckay approved these changes

2021-04-01 16:13 UTC, merged