ODS-5337 Integrate latest 4.0a Data Standard Work
Ed-Fi-Alliance-OSS/Ed-Fi-Extensions pull request #48
Opened 2022-05-17 18:29 UTC by semalaiappan

2022-05-20 16:17 UTC, bptillman requested changes
There were a few license headers that got removed which I commented on, and then in addition to that it appears that updates to the xsd schema files are missing, as you can see here in my local diff I did when copying the files over for TPDM for example
![image](https://user-images.githubusercontent.com/1013553/169570171-65c74522-7484-4b76-8e8f-3628ce439d99.png)

2022-05-20 19:20 UTC, bptillman requested changes
Please double check the Student Transcript and Student Transportation extension packages. There appear to be changes needed for those that are not seen here.

2022-05-23 14:46 UTC, semalaiappan commented on Extensions/EdFi.Ods.Extensions.Sample/Artifacts/MsSql/Structure/Ods/0050-EXTENSION-sample-ExtendedProperties.sql
> --- SPDX-License-Identifier: Apache-2.0
I fixed it . Thanks

2022-05-23 14:47 UTC, semalaiappan commented
> xsd schema files



> There were a few license headers that got removed which I commented on, and then in addition to that it appears that updates to the xsd schema files are missing, as you can see here in my local diff I did when copying the files over for TPDM for example ![image](https://user-images.githubusercontent.com/1013553/169570171-65c74522-7484-4b76-8e8f-3628ce439d99.png)

I added updated xsd schema files in my latest commits

2022-05-23 17:02 UTC, bptillman commented
These changes look good as of now. Not approving and merging yet since more changes will be incoming.

2022-07-05 23:40 UTC, AxelMarquez approved these changes

2022-07-06 15:33 UTC, merged